### ISSUE TITLE
collector: --custom-metadata with "pipe" doesn't work

### ISSUE THREAD

**Issue by Francesco1987** [f18m/cmonitor#44]
I tried to run cmonitor_collector version `2.3.0-0 (commit )` with pipe character as separator (like `--custom-metadata=cmonitor_chart_name:zmq_bg_threads|zmq_gtp|run1|eva-capture-1-edge01-0`) but it fails with this error:
```
bash: run1: command not found...
bash: eva-capture-1-edge01-0: command not found...
bash: zmq_gtp: command not found...
```

**Comment by f18m** [comment]
Hi @Francesco1987 ,
I think the problem is just that pipes need to be escaped in a shell command or enclosed with quotes. Try with:

`
cmonitor_collector --custom-metadata='cmonitor_chart_name:zmq_bg_threads|zmq_gtp|run1|eva-capture-1-edge01-0'
`
