### ISSUE TITLE
Using multiple database for influxdb

### ISSUE THREAD

**Issue by danitome24** [f18m/cmonitor#5]
Hello,

We are using cmonitor for 5 frontends servers. We are setting up a single grafana to monitor all 5 servers with a single influxdb serie database. When using the command cmonitor_collector I see that the default database name on influx must be "cmonitor". Is there a way to change this in order to avoid having an influxdb for each frontend and have all in one influx with multiple databases? 

Thanks for this software, it helped us a lot!

**Comment by f18m** [comment]
Hi @danitome24 ,
I have added a new option named --remote-dbname that you can use on the 5 instances of cmonitor to send the data to 5 different influxDB names, 
Right now the changes are in the branch named "feature/influxdb-name"... can you try out the cmonitor binary from that branch and let me know if it works for you?
If yes, I can merge to master and release a new version!

**Comment by f18m** [comment]
See PR #8

**Comment by f18m** [comment]
Hi @danitome24 ,
I think the PR is pretty safe so I went ahead and merged it!
