### ISSUE TITLE
Prometheus-cpp 1.1.0 upgrade

### ISSUE THREAD

**Issue by sbouchex** [f18m/cmonitor#57]
Prometheus-cpp 1.1.0 upgrade

**Comment by f18m** [comment]
hi @sbouchex ,
Actually in GH what you should do is to open a PR from your fork to this repo. In this case the change is so small that I can push it directly in the main branch though :)

**Comment by f18m** [comment]
Actually I discovered that it's not possible to upgrade prometheus-cpp to 1.1.0 because that supports onyl c++14 which is not available on Centos7, and I don't want to drop support for Centos7 yet...
